# Generated by Django 4.2 on 2025-10-26 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_parking_spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='parkingspace',
            index=models.Index(fields=['city'], name='parking_par_city_ff28cd_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingspace',
            index=models.Index(fields=['status'], name='parking_par_status_769c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingspace',
            index=models.Index(fields=['created_at'], name='parking_par_created_f72991_idx'),
        ),
    ]
