# Generated by Django 4.2 on 2025-10-29 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_commissiondue_commissionsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissiondue',
            name='owner_account',
            field=models.ForeignKey(blank=True, help_text="Link to the owner's commission account", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_dues', to='payments.ownercommissionaccount'),
        ),
    ]
