# Generated by Django 4.2 on 2025-10-29 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0003_bookingpayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_type', models.CharField(choices=[('payment_issue', 'Payment Issue'), ('refund_dispute', 'Refund Dispute'), ('quality_issue', 'Quality Issue'), ('space_unavailable', 'Space Unavailable'), ('damage_claim', 'Damage Claim'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('attachments', models.JSONField(default=list, help_text='List of attachment URLs')),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution_type', models.CharField(blank=True, choices=[('refund_full', 'Full Refund'), ('refund_partial', 'Partial Refund'), ('compensation', 'Compensation'), ('reinstatement', 'Reinstatement'), ('no_action', 'No Action')], max_length=50, null=True)),
                ('resolution_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='bookings.booking')),
                ('other_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_against', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('attachments', models.JSONField(default=list)),
                ('is_internal', models.BooleanField(default=False, help_text='Only visible to admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_comments', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='disputes.dispute')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['booking'], name='disputes_di_booking_48b976_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status'], name='disputes_di_status_124397_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['raised_by'], name='disputes_di_raised__702452_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['created_at'], name='disputes_di_created_ccc858_idx'),
        ),
    ]
