# Generated by Django 4.2 on 2025-10-29 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commission_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('owner_payout_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payout_status', models.CharField(choices=[('pending', 'Pending'), ('due_from_cod', 'Due from COD'), ('settled', 'Settled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_method_used', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='bookings.booking')),
            ],
        ),
    ]
